### ISSUE TITLE
Replace "Brand" on home page UI

### ISSUE THREAD

**Issue by TuOfTimes** [MPCL-McGill/mpclActor#1]
Replace the Brand on the left hand side of the navbar with either a logo. Or alternatively just get rid of it.

**Comment by TuOfTimes** [comment]
Stephen told me that they had a logo in the works for the Actor project. In the meantime I will probably remove it and then update the page when I get the logo

**Comment by alistairpr** [comment]
Okay that's great then, just thought it was a bug. Maybe just replace the
word "Brand" with Actor for now.
